POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "First event",
    "details": "A event that come first in the database",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/6e5063ac-abd2-482f-bda4-c6743aad2b37/attendees
Content-Type: application/json

{
    "name": "Duque",
    "email": "devgduque@gmail.com"
}

### 

GET http://localhost:3333/events/6e5063ac-abd2-482f-bda4-c6743aad2b37

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/4/check-in

### 

GET http://localhost:3333/events/6e5063ac-abd2-482f-bda4-c6743aad2b37/attendees?query=duque